language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"
env:
  - DJANGO="Django>=1.11,<2.0" DB=sqlite
  - DJANGO="Django>=2.0,<2.1" DB=sqlite
  - DJANGO="Django>=2.1,<2.2" DB=sqlite
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1" DB=sqlite
    - python: "2.7"
      env: DJANGO="Django>=2.1,<2.2" DB=sqlite
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2" DB=sqlite
install:
  - export PYTHONPATH=./django_any/:$PYTHONPATH
  - pip install -U $DJANGO
  - pip install -r tests/requirements.pip
script:
  - python tests/manage.py test django_any
